pipeline {
  environment {
    dockerimagename = "f1omactep/nginxapptest"
    dockerImage = ""

  }
  agent any
  stages {
    stage('Checkout Source') {
      steps {
        git branch: 'main', url: 'https://github.com/F1oMaCTeP/App.git'
      }
    }
    stage('Checkout tag') {
      steps{
        script {
          sh 'git fetch'
          gitTag=sh(returnStdout:  true, script: "git tag --sort=-creatordate | head -n 1").trim()
          echo "gitTag output: ${gitTag}"
        }
      }
    }
    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }
    stage('Pushing Image:tags') {
      environment {
               registryCredential = 'dockerhub-credentials'
           }
      steps{
        script {
          docker.withRegistry( 'https://index.docker.io/v1/', registryCredential ) {
            dockerImage.push("${gitTag}")
          }
        }
      }
    }
    stage('sed env') {
      environment {
              envTag = ("${gitTag}")
           }
      steps{
        script {
          sh "sed -i \'18,22 s/gitTag/\'$envTag\'/g\' app.yaml"
          sh 'cat app.yaml'
        }
      }
    }
    stage('Deploying app to Kubernetes') {
      steps {
        script {
          kubernetesDeploy (configs:'app.yaml', kubeconfigId:'k8s-credentials' )
        }
      }
    }
  }
}