all:
  hosts:
    node0:
      ansible_host: 158.160.100.234
      ansible_user: ubuntu
    node1:
      ansible_host: 158.160.73.194
      ansible_user: ubuntu
    node2:
      ansible_host: 51.250.36.92
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node0:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
